# 1. Create a 3x3x3 array with random values 

In [11]:
import numpy as np
np.random.random((3,3,3))

array([[[0.4163597 , 0.89084324, 0.55969802],
        [0.68103243, 0.21453623, 0.87509434],
        [0.48193575, 0.78506111, 0.97798619]],

       [[0.94923898, 0.24902348, 0.85356251],
        [0.87338679, 0.5681179 , 0.43900865],
        [0.24328422, 0.43772985, 0.53713204]],

       [[0.20000544, 0.42212932, 0.76480286],
        [0.23035461, 0.43922738, 0.68573253],
        [0.94346385, 0.29357559, 0.54948465]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [17]:
np.diag(1+np.arange(4),-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [20]:
checker = np.zeros((8,8),dtype = int)
checker[1::2,::2] = 1
checker[::2,1::2] = 1
checker

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [21]:
N = np.random.random((5,5))
Nmax, Nmin = N.max(), N.min()
N = (N - Nmin)/(Nmax - Nmin)
print(N)

[[0.60026669 0.95630926 0.39335231 0.63064963 0.23667725]
 [0.65125328 0.48546028 0.51371593 0.05687539 0.02529844]
 [0.27543017 1.         0.81077213 0.13574014 0.55973889]
 [0.57470803 0.97315015 0.95039225 0.         0.3897519 ]
 [0.02143751 0.19279172 0.43104674 0.00429931 0.68107273]]


# 5.  How to find common values between two arrays?

In [26]:
array1 = np.random.randint(0,15,10)
array2 = np.random.randint(0,15,10)
print(np.intersect1d(array1,array2))

[ 0  3 11]


# 6.How to get the dates of yesterday, today and tomorrow?

In [34]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)
print("Yesterday:",yesterday,"Today:",today,"Tomorrow:",tomorrow)

Yesterday: 2020-07-27 Today: 2020-07-28 Tomorrow: 2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [40]:
array1 = np.random.randint(0,10,10)
array2 = np.random.randint(0,10,10)
eq = np.allclose(array1,array2)
eq

False

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [44]:
vector = np.random.random((10))
vector
max = vector.argmax()
vector[max] = 0
vector

array([0.12974955, 0.5632903 , 0.97240183, 0.        , 0.67592468,
       0.09079965, 0.04192112, 0.5039984 , 0.84932592, 0.20712432])

# 9. How to print all the values of an array?

In [45]:
array = np.random.random((10,10))
print(array)

[[0.68416473 0.23772438 0.85408768 0.76238531 0.81125505 0.73170118
  0.37654989 0.20511552 0.6536116  0.47080255]
 [0.75371309 0.2035814  0.37260215 0.7440034  0.28741838 0.44235216
  0.27847754 0.45644191 0.73249826 0.90951628]
 [0.53436141 0.13467191 0.1462021  0.22332249 0.27570271 0.45053062
  0.56746336 0.78437505 0.3928099  0.9261345 ]
 [0.57953006 0.36047622 0.55602306 0.76167811 0.85552107 0.52616474
  0.79929142 0.69873641 0.46840327 0.715185  ]
 [0.90052675 0.38104105 0.02398965 0.88274196 0.03106997 0.34218168
  0.59702807 0.57664273 0.50277586 0.92232727]
 [0.68085976 0.39155541 0.9320475  0.46409869 0.19871865 0.64966798
  0.06958064 0.28585307 0.78673122 0.23566904]
 [0.27460379 0.17976937 0.8253419  0.05340523 0.73975489 0.97706621
  0.20201523 0.07656692 0.79659996 0.48798767]
 [0.71452961 0.50113547 0.69866734 0.09356345 0.22214843 0.42039308
  0.35514547 0.15304954 0.32740249 0.79854778]
 [0.64612391 0.48187855 0.99486463 0.43588611 0.73270418 0.9983485
  0.83069575 

# 10.Subtract the mean of each row of a matrix

In [46]:
mat = np.random.random((5,5))
print(mat)
mat1 = mat - mat.mean()
print(mat1)

[[0.8252571  0.61557726 0.46158463 0.15671099 0.30064852]
 [0.26359097 0.47667037 0.14487513 0.28939621 0.6668407 ]
 [0.10530243 0.68730589 0.95850944 0.49214879 0.76980956]
 [0.95770738 0.91440654 0.70821538 0.49638995 0.7673322 ]
 [0.86396234 0.06847465 0.73364566 0.93501999 0.65921841]]
[[ 0.25251308  0.04283324 -0.11115939 -0.41603303 -0.2720955 ]
 [-0.30915305 -0.09607365 -0.42786889 -0.28334781  0.09409668]
 [-0.46744159  0.11456187  0.38576542 -0.08059523  0.19706554]
 [ 0.38496336  0.34166252  0.13547136 -0.07635407  0.19458818]
 [ 0.29121832 -0.50426937  0.16090164  0.36227597  0.08647439]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [48]:
vec = np.ones(10)
mat = np.random.randint(0,len(vec),20)
print(vec)
print(mat)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[9 0 5 1 3 7 9 8 5 6 6 8 1 0 0 7 7 6 5 8]


In [49]:
np.add.at(vec, mat, 1)
print(vec)

[4. 3. 1. 2. 1. 4. 4. 4. 4. 3.]


# 12.How to get the diagonal of a dot product?

In [50]:
mat1 = np.random.random((5,5))
mat2 = np.random.random((5,5))
print(np.dot(mat1,mat2))
np.diag(np.dot(mat1,mat2))

[[0.80239667 1.23609914 0.84105145 1.15062974 0.9514375 ]
 [1.15657688 1.46447043 1.03187655 1.44952369 1.52271076]
 [0.57477117 0.89000162 0.59425655 1.19582059 0.82698764]
 [0.78828512 1.09963224 0.72622587 1.50701147 1.12062881]
 [0.62833935 0.76972739 0.59930664 1.26805244 0.99572701]]


array([0.80239667, 1.46447043, 0.59425655, 1.50701147, 0.99572701])

# 13.How to find the most frequent value in an array?

In [55]:
z = np.random.randint(0,10,15)
print(z)
print(np.bincount(z).argmax())

[7 9 6 5 2 0 1 2 5 2 2 1 8 7 9]
2


# 14.How to get the n largest values of an array

In [59]:
arr = np.arange(10000)
n = 10
print (arr[np.argsort(arr)[-n:]])

[9990 9991 9992 9993 9994 9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [61]:
Z = np.array([("Python", 2.5, 3),("MachineLearning", 3.6, 2)])
print(Z)
R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(R)

[['Python' '2.5' '3']
 ['MachineLearning' '3.6' '2']]
[(b'Python', 2.5, 3) (b'MachineL', 3.6, 2)]
